[build]
  command = "pnpm install --no-frozen-lockfile && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/portal"
  to = "https://portal.zagrosia.ca/portal"
  status = 200
  force = true

[[redirects]]
  from = "/portal/*"
  to = "https://portal.zagrosia.ca/portal/:splat"
  status = 200
  force = true
